// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package sqlite

import (
	"context"
)

const createDefaultProject = `-- name: CreateDefaultProject :one
INSERT INTO project ("user", slug, description)
VALUES (?, '', 'Default project')
RETURNING id, created_at, updated_at, user, slug, description
`

func (q *Queries) CreateDefaultProject(ctx context.Context, user string) (Project, error) {
	row := q.db.QueryRowContext(ctx, createDefaultProject, user)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.User,
		&i.Slug,
		&i.Description,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO project ("user", slug, description)
VALUES (?, ?, ?)
RETURNING id, created_at, updated_at, user, slug, description
`

type CreateProjectParams struct {
	User        string `json:"user"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.User, arg.Slug, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.User,
		&i.Slug,
		&i.Description,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM project WHERE "user" = ? AND id = ?
`

type DeleteProjectParams struct {
	User string `json:"user"`
	ID   int64  `json:"id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProject, arg.User, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDefaultProject = `-- name: GetDefaultProject :one
SELECT id, created_at, updated_at, user, slug, description FROM project WHERE "user" = ? AND slug = ''
`

func (q *Queries) GetDefaultProject(ctx context.Context, user string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getDefaultProject, user)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.User,
		&i.Slug,
		&i.Description,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, created_at, updated_at, user, slug, description FROM project WHERE "user" = ? AND id = ?
`

type GetProjectParams struct {
	User string `json:"user"`
	ID   int64  `json:"id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, arg.User, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.User,
		&i.Slug,
		&i.Description,
	)
	return i, err
}

const listAllProjects = `-- name: ListAllProjects :many
SELECT id, created_at, updated_at, user, slug, description FROM project
`

func (q *Queries) ListAllProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.User,
			&i.Slug,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, created_at, updated_at, user, slug, description FROM project WHERE "user" = ? ORDER BY id ASC
`

func (q *Queries) ListProjects(ctx context.Context, user string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.User,
			&i.Slug,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectExists = `-- name: ProjectExists :one
SELECT EXISTS(SELECT 1 FROM project WHERE "user" = ? AND id = ?) AS ok
`

type ProjectExistsParams struct {
	User string `json:"user"`
	ID   int64  `json:"id"`
}

func (q *Queries) ProjectExists(ctx context.Context, arg ProjectExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, projectExists, arg.User, arg.ID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const updateProject = `-- name: UpdateProject :execrows
UPDATE project SET description = ?, updated_at = current_timestamp
WHERE "user" = ? AND id = ?
`

type UpdateProjectParams struct {
	Description string `json:"description"`
	User        string `json:"user"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProject, arg.Description, arg.User, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
