// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token.sql

package sqlite

import (
	"context"
	"time"

	"github.com/reddec/token-login/internal/types"
)

const createToken = `-- name: CreateToken :one
INSERT INTO token (key_id, hash, user, label, path, host, headers, project_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_at, updated_at, key_id, hash, user, label, path, host, headers, requests, last_access_at, project_id
`

type CreateTokenParams struct {
	KeyID     types.KeyID   `json:"key_id"`
	Hash      []byte        `json:"hash"`
	User      string        `json:"user"`
	Label     string        `json:"label"`
	Path      string        `json:"path"`
	Host      string        `json:"host"`
	Headers   types.Headers `json:"headers"`
	ProjectID int64         `json:"project_id"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.KeyID,
		arg.Hash,
		arg.User,
		arg.Label,
		arg.Path,
		arg.Host,
		arg.Headers,
		arg.ProjectID,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyID,
		&i.Hash,
		&i.User,
		&i.Label,
		&i.Path,
		&i.Host,
		&i.Headers,
		&i.Requests,
		&i.LastAccessAt,
		&i.ProjectID,
	)
	return i, err
}

const deleteToken = `-- name: DeleteToken :execrows
DELETE FROM token WHERE user = ? AND id = ?
`

type DeleteTokenParams struct {
	User string `json:"user"`
	ID   int64  `json:"id"`
}

func (q *Queries) DeleteToken(ctx context.Context, arg DeleteTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteToken, arg.User, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getToken = `-- name: GetToken :one
SELECT id, created_at, updated_at, key_id, hash, user, label, path, host, headers, requests, last_access_at, project_id, project_slug FROM token_view WHERE user = ? AND id = ?
`

type GetTokenParams struct {
	User string `json:"user"`
	ID   int64  `json:"id"`
}

func (q *Queries) GetToken(ctx context.Context, arg GetTokenParams) (TokenView, error) {
	row := q.db.QueryRowContext(ctx, getToken, arg.User, arg.ID)
	var i TokenView
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyID,
		&i.Hash,
		&i.User,
		&i.Label,
		&i.Path,
		&i.Host,
		&i.Headers,
		&i.Requests,
		&i.LastAccessAt,
		&i.ProjectID,
		&i.ProjectSlug,
	)
	return i, err
}

const getTokenByID = `-- name: GetTokenByID :one
SELECT id, created_at, updated_at, key_id, hash, user, label, path, host, headers, requests, last_access_at, project_id, project_slug FROM token_view WHERE id = ?
`

func (q *Queries) GetTokenByID(ctx context.Context, id int64) (TokenView, error) {
	row := q.db.QueryRowContext(ctx, getTokenByID, id)
	var i TokenView
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyID,
		&i.Hash,
		&i.User,
		&i.Label,
		&i.Path,
		&i.Host,
		&i.Headers,
		&i.Requests,
		&i.LastAccessAt,
		&i.ProjectID,
		&i.ProjectSlug,
	)
	return i, err
}

const listAllTokens = `-- name: ListAllTokens :many
SELECT id, created_at, updated_at, key_id, hash, user, label, path, host, headers, requests, last_access_at, project_id, project_slug FROM token_view
`

func (q *Queries) ListAllTokens(ctx context.Context) ([]TokenView, error) {
	rows, err := q.db.QueryContext(ctx, listAllTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TokenView{}
	for rows.Next() {
		var i TokenView
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KeyID,
			&i.Hash,
			&i.User,
			&i.Label,
			&i.Path,
			&i.Host,
			&i.Headers,
			&i.Requests,
			&i.LastAccessAt,
			&i.ProjectID,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenIDsByProject = `-- name: ListTokenIDsByProject :many
SELECT id FROM token WHERE project_id = ?
`

func (q *Queries) ListTokenIDsByProject(ctx context.Context, projectID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listTokenIDsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokens = `-- name: ListTokens :many
SELECT id, created_at, updated_at, key_id, hash, user, label, path, host, headers, requests, last_access_at, project_id, project_slug FROM token_view WHERE user = ? ORDER BY id DESC
`

func (q *Queries) ListTokens(ctx context.Context, user string) ([]TokenView, error) {
	rows, err := q.db.QueryContext(ctx, listTokens, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TokenView{}
	for rows.Next() {
		var i TokenView
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KeyID,
			&i.Hash,
			&i.User,
			&i.Label,
			&i.Path,
			&i.Host,
			&i.Headers,
			&i.Requests,
			&i.LastAccessAt,
			&i.ProjectID,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensByUserAndProject = `-- name: ListTokensByUserAndProject :many
SELECT id, created_at, updated_at, key_id, hash, user, label, path, host, headers, requests, last_access_at, project_id, project_slug FROM token_view WHERE user = ? AND project_id = ? ORDER BY id DESC
`

type ListTokensByUserAndProjectParams struct {
	User      string `json:"user"`
	ProjectID int64  `json:"project_id"`
}

func (q *Queries) ListTokensByUserAndProject(ctx context.Context, arg ListTokensByUserAndProjectParams) ([]TokenView, error) {
	rows, err := q.db.QueryContext(ctx, listTokensByUserAndProject, arg.User, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TokenView{}
	for rows.Next() {
		var i TokenView
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KeyID,
			&i.Hash,
			&i.User,
			&i.Label,
			&i.Path,
			&i.Host,
			&i.Headers,
			&i.Requests,
			&i.LastAccessAt,
			&i.ProjectID,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshToken = `-- name: RefreshToken :execrows
UPDATE token
SET hash = ?, key_id = ?, updated_at = current_timestamp
WHERE user = ? AND id = ?
`

type RefreshTokenParams struct {
	Hash  []byte      `json:"hash"`
	KeyID types.KeyID `json:"key_id"`
	User  string      `json:"user"`
	ID    int64       `json:"id"`
}

func (q *Queries) RefreshToken(ctx context.Context, arg RefreshTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, refreshToken,
		arg.Hash,
		arg.KeyID,
		arg.User,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateToken = `-- name: UpdateToken :execrows
UPDATE token
SET host = ?, path = ?, label = ?, headers = ?, updated_at = current_timestamp
WHERE user = ? AND id = ?
`

type UpdateTokenParams struct {
	Host    string        `json:"host"`
	Path    string        `json:"path"`
	Label   string        `json:"label"`
	Headers types.Headers `json:"headers"`
	User    string        `json:"user"`
	ID      int64         `json:"id"`
}

func (q *Queries) UpdateToken(ctx context.Context, arg UpdateTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateToken,
		arg.Host,
		arg.Path,
		arg.Label,
		arg.Headers,
		arg.User,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTokenStats = `-- name: UpdateTokenStats :exec
UPDATE token
SET requests = requests + ?1, last_access_at = ?2, updated_at = current_timestamp
WHERE id = ?3
`

type UpdateTokenStatsParams struct {
	Requests     int64     `json:"requests"`
	LastAccessAt time.Time `json:"last_access_at"`
	ID           int64     `json:"id"`
}

func (q *Queries) UpdateTokenStats(ctx context.Context, arg UpdateTokenStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateTokenStats, arg.Requests, arg.LastAccessAt, arg.ID)
	return err
}
