services:
  tokens:
    image: ghcr.io/reddec/token-login:1
    restart: unless-stopped
    volumes:
      - tokens:/data

  backend:
    image: daime/http-dump:latest
    restart: unless-stopped

  proxy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - tokens
      - backend
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
volumes:
  tokens: {}