version: "2"

run:
  tests: false

linters:
  default: all
  disable:
    - errcheck
    - tagalign
    - noinlineerr
    - nlreturn
    - lll
    - wsl
    - wsl_v5
    - gocognit
    - depguard
    - cyclop
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - govet
        text: "inline:"
      - linters:
          - gosec
        path: internal/utils/utils.go
        text: "G124"
      - linters:
          - contextcheck
        path: cmd/token-login/main.go
        text: "Non-inherited new context"
      - linters:
          - recvcheck
        path: internal/types/types.go
        text: "KeyID"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
