version: "2"

run:
  tests: false

linters:
  default: all
  disable:
    - errcheck
    - tagalign
    - noinlineerr
    - nlreturn
    - lll
    - wsl
    - wsl_v5
    - gocognit
    - depguard
    - cyclop
    - exhaustruct
    - tagliatelle
    - varnamelen
    - funcorder
    - ireturn
    - interfacebloat
    - goconst
    - funlen
    - nonamedreturns
    - mnd
    - revive
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - node_modules$
    rules:
      - linters:
          - gosec
        path: internal/utils/utils.go
        text: "G124"
      - linters:
          - gosec
        path: internal/dbo/open/open.go
        text: "G104"
      - linters:
          - contextcheck
        path: cmd/token-login/main.go
        text: "Non-inherited new context"
      - linters:
          - recvcheck
        path: internal/types/types.go
        text: "KeyID"
      - linters:
          - recvcheck
        path: internal/types/types.go
        text: "Headers"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - node_modules$
