run:
  tests: false
linters:
  enable-all: true
  disable:
    - goerr113
    - contextcheck
    - exhaustivestruct
    - wrapcheck
    - varnamelen
    - exhaustruct
    - lll
    - wsl
    - nlreturn
    - gofumpt
    - funlen
    - gci
    - nonamedreturns
    - interfacer
    - maligned
    - tagalign
    - depguard
    - structcheck