builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    flags:
      - -trimpath
    goarch:
      - arm64
      - amd64
    main: ./cmd/token-login/main.go
    binary: token-login
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
dockers:
  - image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
  # alias for latest
  - name_template: "ghcr.io/reddec/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
  # alias for major version (x)
  - name_template: "ghcr.io/reddec/{{ .ProjectName }}:{{.Major}}"
    image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
  # alias for minor version (x.y)
  - name_template: "ghcr.io/reddec/{{ .ProjectName }}:{{.Major}}.{{.Minor}}"
    image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'