// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TokenColumns holds the columns for the "token" table.
	TokenColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true, SchemaType: map[string]string{"postgres": "bigserial"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "key_id", Type: field.TypeString, Unique: true},
		{Name: "hash", Type: field.TypeBytes},
		{Name: "user", Type: field.TypeString},
		{Name: "label", Type: field.TypeString, Default: ""},
		{Name: "path", Type: field.TypeString, Default: "/**"},
		{Name: "host", Type: field.TypeString, Default: ""},
		{Name: "headers", Type: field.TypeJSON, Nullable: true},
		{Name: "requests", Type: field.TypeInt64, Default: 0},
		{Name: "last_access_at", Type: field.TypeTime},
	}
	// TokenTable holds the schema information for the "token" table.
	TokenTable = &schema.Table{
		Name:       "token",
		Columns:    TokenColumns,
		PrimaryKey: []*schema.Column{TokenColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "token_user",
				Unique:  false,
				Columns: []*schema.Column{TokenColumns[5]},
			},
			{
				Name:    "token_key_id",
				Unique:  true,
				Columns: []*schema.Column{TokenColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TokenTable,
	}
)

func init() {
	TokenTable.Annotation = &entsql.Annotation{
		Table: "token",
	}
}
