// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"encoding/json"
	"time"

	"github.com/reddec/token-login/internal/types"
)

type Project struct {
	ID          int64     `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	User        string    `json:"user"`
	Slug        string    `json:"slug"`
	Description string    `json:"description"`
}

type Token struct {
	ID           int64           `json:"id"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	KeyID        types.KeyID     `json:"key_id"`
	Hash         []byte          `json:"hash"`
	User         string          `json:"user"`
	Label        string          `json:"label"`
	Headers      types.Headers   `json:"headers"`
	Requests     int64           `json:"requests"`
	LastAccessAt time.Time       `json:"last_access_at"`
	ProjectID    int64           `json:"project_id"`
	Hosts        json.RawMessage `json:"hosts"`
	Paths        json.RawMessage `json:"paths"`
}

type TokenView struct {
	ID           int64           `json:"id"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	KeyID        types.KeyID     `json:"key_id"`
	Hash         []byte          `json:"hash"`
	User         string          `json:"user"`
	Label        string          `json:"label"`
	Hosts        json.RawMessage `json:"hosts"`
	Paths        json.RawMessage `json:"paths"`
	Headers      types.Headers   `json:"headers"`
	Requests     int64           `json:"requests"`
	LastAccessAt time.Time       `json:"last_access_at"`
	ProjectID    int64           `json:"project_id"`
	ProjectSlug  string          `json:"project_slug"`
}
