// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token.sql

package postgres

import (
	"context"
	"time"

	"github.com/reddec/token-login/internal/types"
)

const createToken = `-- name: CreateToken :one
INSERT INTO token (key_id, hash, "user", label, path, host, headers, project_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, created_at, updated_at, key_id, hash, "user", label, path, headers, requests, last_access_at, host, project_id
`

type CreateTokenParams struct {
	KeyID     types.KeyID `json:"key_id"`
	Hash      []byte      `json:"hash"`
	User      string      `json:"user"`
	Label     string      `json:"label"`
	Path      string      `json:"path"`
	Host      string      `json:"host"`
	Headers   []byte      `json:"headers"`
	ProjectID int64       `json:"project_id"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.KeyID,
		arg.Hash,
		arg.User,
		arg.Label,
		arg.Path,
		arg.Host,
		arg.Headers,
		arg.ProjectID,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyID,
		&i.Hash,
		&i.User,
		&i.Label,
		&i.Path,
		&i.Headers,
		&i.Requests,
		&i.LastAccessAt,
		&i.Host,
		&i.ProjectID,
	)
	return i, err
}

const deleteToken = `-- name: DeleteToken :execrows
DELETE FROM token WHERE "user" = $1 AND id = $2
`

type DeleteTokenParams struct {
	User string `json:"user"`
	ID   int64  `json:"id"`
}

func (q *Queries) DeleteToken(ctx context.Context, arg DeleteTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToken, arg.User, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getToken = `-- name: GetToken :one
SELECT id, created_at, updated_at, key_id, hash, "user", label, path, host, headers, requests, last_access_at, project_id, project_slug FROM token_view WHERE "user" = $1 AND id = $2
`

type GetTokenParams struct {
	User string `json:"user"`
	ID   int64  `json:"id"`
}

func (q *Queries) GetToken(ctx context.Context, arg GetTokenParams) (TokenView, error) {
	row := q.db.QueryRow(ctx, getToken, arg.User, arg.ID)
	var i TokenView
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyID,
		&i.Hash,
		&i.User,
		&i.Label,
		&i.Path,
		&i.Host,
		&i.Headers,
		&i.Requests,
		&i.LastAccessAt,
		&i.ProjectID,
		&i.ProjectSlug,
	)
	return i, err
}

const getTokenByID = `-- name: GetTokenByID :one
SELECT id, created_at, updated_at, key_id, hash, "user", label, path, host, headers, requests, last_access_at, project_id, project_slug FROM token_view WHERE id = $1
`

func (q *Queries) GetTokenByID(ctx context.Context, id int64) (TokenView, error) {
	row := q.db.QueryRow(ctx, getTokenByID, id)
	var i TokenView
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyID,
		&i.Hash,
		&i.User,
		&i.Label,
		&i.Path,
		&i.Host,
		&i.Headers,
		&i.Requests,
		&i.LastAccessAt,
		&i.ProjectID,
		&i.ProjectSlug,
	)
	return i, err
}

const listAllTokens = `-- name: ListAllTokens :many
SELECT id, created_at, updated_at, key_id, hash, "user", label, path, host, headers, requests, last_access_at, project_id, project_slug FROM token_view
`

func (q *Queries) ListAllTokens(ctx context.Context) ([]TokenView, error) {
	rows, err := q.db.Query(ctx, listAllTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TokenView{}
	for rows.Next() {
		var i TokenView
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KeyID,
			&i.Hash,
			&i.User,
			&i.Label,
			&i.Path,
			&i.Host,
			&i.Headers,
			&i.Requests,
			&i.LastAccessAt,
			&i.ProjectID,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenIDsByProject = `-- name: ListTokenIDsByProject :many
SELECT id FROM token WHERE project_id = $1
`

func (q *Queries) ListTokenIDsByProject(ctx context.Context, projectID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listTokenIDsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokens = `-- name: ListTokens :many
SELECT id, created_at, updated_at, key_id, hash, "user", label, path, host, headers, requests, last_access_at, project_id, project_slug FROM token_view WHERE "user" = $1 ORDER BY id DESC
`

func (q *Queries) ListTokens(ctx context.Context, user string) ([]TokenView, error) {
	rows, err := q.db.Query(ctx, listTokens, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TokenView{}
	for rows.Next() {
		var i TokenView
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KeyID,
			&i.Hash,
			&i.User,
			&i.Label,
			&i.Path,
			&i.Host,
			&i.Headers,
			&i.Requests,
			&i.LastAccessAt,
			&i.ProjectID,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensByUserAndProject = `-- name: ListTokensByUserAndProject :many
SELECT id, created_at, updated_at, key_id, hash, "user", label, path, host, headers, requests, last_access_at, project_id, project_slug FROM token_view WHERE "user" = $1 AND project_id = $2 ORDER BY id DESC
`

type ListTokensByUserAndProjectParams struct {
	User      string `json:"user"`
	ProjectID int64  `json:"project_id"`
}

func (q *Queries) ListTokensByUserAndProject(ctx context.Context, arg ListTokensByUserAndProjectParams) ([]TokenView, error) {
	rows, err := q.db.Query(ctx, listTokensByUserAndProject, arg.User, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TokenView{}
	for rows.Next() {
		var i TokenView
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KeyID,
			&i.Hash,
			&i.User,
			&i.Label,
			&i.Path,
			&i.Host,
			&i.Headers,
			&i.Requests,
			&i.LastAccessAt,
			&i.ProjectID,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshToken = `-- name: RefreshToken :execrows
UPDATE token
SET hash = $1, key_id = $2, updated_at = now()
WHERE "user" = $3 AND id = $4
`

type RefreshTokenParams struct {
	Hash  []byte      `json:"hash"`
	KeyID types.KeyID `json:"key_id"`
	User  string      `json:"user"`
	ID    int64       `json:"id"`
}

func (q *Queries) RefreshToken(ctx context.Context, arg RefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, refreshToken,
		arg.Hash,
		arg.KeyID,
		arg.User,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateToken = `-- name: UpdateToken :execrows
UPDATE token
SET host = $1, path = $2, label = $3, headers = $4, updated_at = now()
WHERE "user" = $5 AND id = $6
`

type UpdateTokenParams struct {
	Host    string `json:"host"`
	Path    string `json:"path"`
	Label   string `json:"label"`
	Headers []byte `json:"headers"`
	User    string `json:"user"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateToken(ctx context.Context, arg UpdateTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateToken,
		arg.Host,
		arg.Path,
		arg.Label,
		arg.Headers,
		arg.User,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTokenStats = `-- name: UpdateTokenStats :exec
UPDATE token
SET requests = requests + $1, last_access_at = $2, updated_at = now()
WHERE id = $3
`

type UpdateTokenStatsParams struct {
	Requests     int64     `json:"requests"`
	LastAccessAt time.Time `json:"last_access_at"`
	ID           int64     `json:"id"`
}

func (q *Queries) UpdateTokenStats(ctx context.Context, arg UpdateTokenStatsParams) error {
	_, err := q.db.Exec(ctx, updateTokenStats, arg.Requests, arg.LastAccessAt, arg.ID)
	return err
}
