// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/reddec/token-login/internal/ent/predicate"
	"github.com/reddec/token-login/internal/ent/project"
	"github.com/reddec/token-login/internal/ent/token"
	"github.com/reddec/token-login/internal/types"
)

// TokenUpdate is the builder for updating Token entities.
type TokenUpdate struct {
	config
	hooks    []Hook
	mutation *TokenMutation
}

// Where appends a list predicates to the TokenUpdate builder.
func (_u *TokenUpdate) Where(ps ...predicate.Token) *TokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TokenUpdate) SetCreatedAt(v time.Time) *TokenUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TokenUpdate) SetNillableCreatedAt(v *time.Time) *TokenUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TokenUpdate) SetUpdatedAt(v time.Time) *TokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKeyID sets the "key_id" field.
func (_u *TokenUpdate) SetKeyID(v *types.KeyID) *TokenUpdate {
	_u.mutation.SetKeyID(v)
	return _u
}

// SetHash sets the "hash" field.
func (_u *TokenUpdate) SetHash(v []byte) *TokenUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetUser sets the "user" field.
func (_u *TokenUpdate) SetUser(v string) *TokenUpdate {
	_u.mutation.SetUser(v)
	return _u
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (_u *TokenUpdate) SetNillableUser(v *string) *TokenUpdate {
	if v != nil {
		_u.SetUser(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *TokenUpdate) SetLabel(v string) *TokenUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *TokenUpdate) SetNillableLabel(v *string) *TokenUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *TokenUpdate) SetPath(v string) *TokenUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *TokenUpdate) SetNillablePath(v *string) *TokenUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *TokenUpdate) SetHost(v string) *TokenUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *TokenUpdate) SetNillableHost(v *string) *TokenUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *TokenUpdate) SetHeaders(v types.Headers) *TokenUpdate {
	_u.mutation.SetHeaders(v)
	return _u
}

// AppendHeaders appends value to the "headers" field.
func (_u *TokenUpdate) AppendHeaders(v types.Headers) *TokenUpdate {
	_u.mutation.AppendHeaders(v)
	return _u
}

// ClearHeaders clears the value of the "headers" field.
func (_u *TokenUpdate) ClearHeaders() *TokenUpdate {
	_u.mutation.ClearHeaders()
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *TokenUpdate) SetProjectID(v int) *TokenUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *TokenUpdate) SetNillableProjectID(v *int) *TokenUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *TokenUpdate) ClearProjectID() *TokenUpdate {
	_u.mutation.ClearProjectID()
	return _u
}

// SetRequests sets the "requests" field.
func (_u *TokenUpdate) SetRequests(v int64) *TokenUpdate {
	_u.mutation.ResetRequests()
	_u.mutation.SetRequests(v)
	return _u
}

// SetNillableRequests sets the "requests" field if the given value is not nil.
func (_u *TokenUpdate) SetNillableRequests(v *int64) *TokenUpdate {
	if v != nil {
		_u.SetRequests(*v)
	}
	return _u
}

// AddRequests adds value to the "requests" field.
func (_u *TokenUpdate) AddRequests(v int64) *TokenUpdate {
	_u.mutation.AddRequests(v)
	return _u
}

// SetLastAccessAt sets the "last_access_at" field.
func (_u *TokenUpdate) SetLastAccessAt(v time.Time) *TokenUpdate {
	_u.mutation.SetLastAccessAt(v)
	return _u
}

// SetNillableLastAccessAt sets the "last_access_at" field if the given value is not nil.
func (_u *TokenUpdate) SetNillableLastAccessAt(v *time.Time) *TokenUpdate {
	if v != nil {
		_u.SetLastAccessAt(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *TokenUpdate) SetProject(v *Project) *TokenUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the TokenMutation object of the builder.
func (_u *TokenUpdate) Mutation() *TokenMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *TokenUpdate) ClearProject() *TokenUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := token.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TokenUpdate) check() error {
	if v, ok := _u.mutation.Hash(); ok {
		if err := token.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "Token.hash": %w`, err)}
		}
	}
	return nil
}

func (_u *TokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(token.Table, token.Columns, sqlgraph.NewFieldSpec(token.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(token.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(token.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.KeyID(); ok {
		vv, err := token.ValueScanner.KeyID.Value(value)
		if err != nil {
			return 0, err
		}
		_spec.SetField(token.FieldKeyID, field.TypeString, vv)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(token.FieldHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.User(); ok {
		_spec.SetField(token.FieldUser, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(token.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(token.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(token.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(token.FieldHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedHeaders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, token.FieldHeaders, value)
		})
	}
	if _u.mutation.HeadersCleared() {
		_spec.ClearField(token.FieldHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.Requests(); ok {
		_spec.SetField(token.FieldRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequests(); ok {
		_spec.AddField(token.FieldRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastAccessAt(); ok {
		_spec.SetField(token.FieldLastAccessAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   token.ProjectTable,
			Columns: []string{token.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   token.ProjectTable,
			Columns: []string{token.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{token.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TokenUpdateOne is the builder for updating a single Token entity.
type TokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TokenMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *TokenUpdateOne) SetCreatedAt(v time.Time) *TokenUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TokenUpdateOne) SetNillableCreatedAt(v *time.Time) *TokenUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TokenUpdateOne) SetUpdatedAt(v time.Time) *TokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKeyID sets the "key_id" field.
func (_u *TokenUpdateOne) SetKeyID(v *types.KeyID) *TokenUpdateOne {
	_u.mutation.SetKeyID(v)
	return _u
}

// SetHash sets the "hash" field.
func (_u *TokenUpdateOne) SetHash(v []byte) *TokenUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetUser sets the "user" field.
func (_u *TokenUpdateOne) SetUser(v string) *TokenUpdateOne {
	_u.mutation.SetUser(v)
	return _u
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (_u *TokenUpdateOne) SetNillableUser(v *string) *TokenUpdateOne {
	if v != nil {
		_u.SetUser(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *TokenUpdateOne) SetLabel(v string) *TokenUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *TokenUpdateOne) SetNillableLabel(v *string) *TokenUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *TokenUpdateOne) SetPath(v string) *TokenUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *TokenUpdateOne) SetNillablePath(v *string) *TokenUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *TokenUpdateOne) SetHost(v string) *TokenUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *TokenUpdateOne) SetNillableHost(v *string) *TokenUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *TokenUpdateOne) SetHeaders(v types.Headers) *TokenUpdateOne {
	_u.mutation.SetHeaders(v)
	return _u
}

// AppendHeaders appends value to the "headers" field.
func (_u *TokenUpdateOne) AppendHeaders(v types.Headers) *TokenUpdateOne {
	_u.mutation.AppendHeaders(v)
	return _u
}

// ClearHeaders clears the value of the "headers" field.
func (_u *TokenUpdateOne) ClearHeaders() *TokenUpdateOne {
	_u.mutation.ClearHeaders()
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *TokenUpdateOne) SetProjectID(v int) *TokenUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *TokenUpdateOne) SetNillableProjectID(v *int) *TokenUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *TokenUpdateOne) ClearProjectID() *TokenUpdateOne {
	_u.mutation.ClearProjectID()
	return _u
}

// SetRequests sets the "requests" field.
func (_u *TokenUpdateOne) SetRequests(v int64) *TokenUpdateOne {
	_u.mutation.ResetRequests()
	_u.mutation.SetRequests(v)
	return _u
}

// SetNillableRequests sets the "requests" field if the given value is not nil.
func (_u *TokenUpdateOne) SetNillableRequests(v *int64) *TokenUpdateOne {
	if v != nil {
		_u.SetRequests(*v)
	}
	return _u
}

// AddRequests adds value to the "requests" field.
func (_u *TokenUpdateOne) AddRequests(v int64) *TokenUpdateOne {
	_u.mutation.AddRequests(v)
	return _u
}

// SetLastAccessAt sets the "last_access_at" field.
func (_u *TokenUpdateOne) SetLastAccessAt(v time.Time) *TokenUpdateOne {
	_u.mutation.SetLastAccessAt(v)
	return _u
}

// SetNillableLastAccessAt sets the "last_access_at" field if the given value is not nil.
func (_u *TokenUpdateOne) SetNillableLastAccessAt(v *time.Time) *TokenUpdateOne {
	if v != nil {
		_u.SetLastAccessAt(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *TokenUpdateOne) SetProject(v *Project) *TokenUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the TokenMutation object of the builder.
func (_u *TokenUpdateOne) Mutation() *TokenMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *TokenUpdateOne) ClearProject() *TokenUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the TokenUpdate builder.
func (_u *TokenUpdateOne) Where(ps ...predicate.Token) *TokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TokenUpdateOne) Select(field string, fields ...string) *TokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Token entity.
func (_u *TokenUpdateOne) Save(ctx context.Context) (*Token, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TokenUpdateOne) SaveX(ctx context.Context) *Token {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := token.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TokenUpdateOne) check() error {
	if v, ok := _u.mutation.Hash(); ok {
		if err := token.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "Token.hash": %w`, err)}
		}
	}
	return nil
}

func (_u *TokenUpdateOne) sqlSave(ctx context.Context) (_node *Token, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(token.Table, token.Columns, sqlgraph.NewFieldSpec(token.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Token.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, token.FieldID)
		for _, f := range fields {
			if !token.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != token.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(token.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(token.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.KeyID(); ok {
		vv, err := token.ValueScanner.KeyID.Value(value)
		if err != nil {
			return nil, err
		}
		_spec.SetField(token.FieldKeyID, field.TypeString, vv)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(token.FieldHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.User(); ok {
		_spec.SetField(token.FieldUser, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(token.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(token.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(token.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(token.FieldHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedHeaders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, token.FieldHeaders, value)
		})
	}
	if _u.mutation.HeadersCleared() {
		_spec.ClearField(token.FieldHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.Requests(); ok {
		_spec.SetField(token.FieldRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequests(); ok {
		_spec.AddField(token.FieldRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastAccessAt(); ok {
		_spec.SetField(token.FieldLastAccessAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   token.ProjectTable,
			Columns: []string{token.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   token.ProjectTable,
			Columns: []string{token.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Token{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{token.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
