// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// TokenOrErr calls the predicate only if the error is not nit.
func TokenOrErr(p Token, err error) Token {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}
