services:
  tokens:
    image: ghcr.io/reddec/token-login:1
    restart: unless-stopped
    volumes:
      - tokens:/data

  backend:
    image: daime/http-dump:latest
    restart: unless-stopped

  proxy:
    image: nginx
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - tokens
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  tokens: {}