// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateProjectData, CreateProjectResponses, CreateTokenData, CreateTokenResponses, DeleteProjectData, DeleteProjectResponses, DeleteTokenData, DeleteTokenResponses, GetProjectData, GetProjectResponses, GetTokenData, GetTokenResponses, ListProjectsData, ListProjectsResponses, ListTokensData, ListTokensResponses, RefreshTokenData, RefreshTokenResponses, UpdateProjectData, UpdateProjectResponses, UpdateTokenData, UpdateTokenResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List all projects
 */
export const listProjects = <ThrowOnError extends boolean = false>(options?: Options<ListProjectsData, ThrowOnError>): RequestResult<ListProjectsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListProjectsResponses, unknown, ThrowOnError>({ url: '/projects', ...options });

/**
 * Create new project
 */
export const createProject = <ThrowOnError extends boolean = false>(options: Options<CreateProjectData, ThrowOnError>): RequestResult<CreateProjectResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateProjectResponses, unknown, ThrowOnError>({
    url: '/projects',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete project
 */
export const deleteProject = <ThrowOnError extends boolean = false>(options: Options<DeleteProjectData, ThrowOnError>): RequestResult<DeleteProjectResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteProjectResponses, unknown, ThrowOnError>({ url: '/projects/{project}', ...options });

/**
 * Get project by ID
 */
export const getProject = <ThrowOnError extends boolean = false>(options: Options<GetProjectData, ThrowOnError>): RequestResult<GetProjectResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetProjectResponses, unknown, ThrowOnError>({ url: '/projects/{project}', ...options });

/**
 * Update project. Supports partial update.
 */
export const updateProject = <ThrowOnError extends boolean = false>(options: Options<UpdateProjectData, ThrowOnError>): RequestResult<UpdateProjectResponses, unknown, ThrowOnError> => (options.client ?? client).patch<UpdateProjectResponses, unknown, ThrowOnError>({
    url: '/projects/{project}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all tokens for user
 */
export const listTokens = <ThrowOnError extends boolean = false>(options?: Options<ListTokensData, ThrowOnError>): RequestResult<ListTokensResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListTokensResponses, unknown, ThrowOnError>({ url: '/tokens', ...options });

/**
 * Create new token for user
 */
export const createToken = <ThrowOnError extends boolean = false>(options: Options<CreateTokenData, ThrowOnError>): RequestResult<CreateTokenResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateTokenResponses, unknown, ThrowOnError>({
    url: '/tokens',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete token for user
 */
export const deleteToken = <ThrowOnError extends boolean = false>(options: Options<DeleteTokenData, ThrowOnError>): RequestResult<DeleteTokenResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteTokenResponses, unknown, ThrowOnError>({ url: '/tokens/{token}', ...options });

/**
 * Get tokens by ID and for the current user
 */
export const getToken = <ThrowOnError extends boolean = false>(options: Options<GetTokenData, ThrowOnError>): RequestResult<GetTokenResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetTokenResponses, unknown, ThrowOnError>({ url: '/tokens/{token}', ...options });

/**
 * Update token for user. Supports partial update.
 */
export const updateToken = <ThrowOnError extends boolean = false>(options: Options<UpdateTokenData, ThrowOnError>): RequestResult<UpdateTokenResponses, unknown, ThrowOnError> => (options.client ?? client).patch<UpdateTokenResponses, unknown, ThrowOnError>({
    url: '/tokens/{token}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Regenerate token key
 */
export const refreshToken = <ThrowOnError extends boolean = false>(options: Options<RefreshTokenData, ThrowOnError>): RequestResult<RefreshTokenResponses, unknown, ThrowOnError> => (options.client ?? client).post<RefreshTokenResponses, unknown, ThrowOnError>({ url: '/tokens/{token}', ...options });
