// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type Project = {
    /**
     * Unique project ID
     */
    id: number;
    /**
     * Time when project was created
     */
    createdAt: string;
    /**
     * Time when project was last updated
     */
    updatedAt: string;
    /**
     * Unique project slug (path and query friendly)
     */
    slug: string;
    /**
     * Project description
     */
    description: string;
};

export type ProjectPatch = {
    /**
     * Project description
     */
    description?: string;
};

export type ProjectConfig = {
    /**
     * Unique project slug (path and query friendly)
     */
    slug: string;
    /**
     * Project description
     */
    description?: string;
};

export type NameValue = {
    name: string;
    value: string;
};

export type Credential = {
    /**
     * Token ID
     */
    id: number;
    /**
     * Raw token key
     */
    key: string;
};

export type TokenPatch = {
    /**
     * Custom token description
     */
    label?: string;
    /**
     * Allowed hosts. Supports globs. Empty means "allow all"
     */
    host?: string;
    /**
     * Allowed path. Supports globs. Empty means "allow all"
     */
    path?: string;
    /**
     * Custom headers which will be added after successfull authorization
     */
    headers?: Array<NameValue>;
};

export type TokenConfig = {
    /**
     * Custom token description
     */
    label?: string;
    /**
     * Allowed hosts. Supports globs. Empty means "allow all"
     */
    host?: string;
    /**
     * Allowed path. Supports globs. Empty means "allow all"
     */
    path?: string;
    /**
     * Custom headers which will be added after successfull authorization
     */
    headers?: Array<NameValue>;
    /**
     * Project ID this token belongs to
     */
    projectId: number;
};

export type Token = {
    /**
     * Unique token ID
     */
    id: number;
    /**
     * Time when token was initially created
     */
    createdAt: string;
    /**
     * Time when token was updated last time
     */
    updatedAt: string;
    /**
     * Tentative time when token was last time used
     */
    lastAccessAt?: string;
    /**
     * Unique first several bytes for token which is used for fast identification
     */
    keyID: string;
    /**
     * User which created token
     */
    user: string;
    /**
     * Custom token description
     */
    label: string;
    /**
     * Allowed hosts. Supports globs. Empty means "allow all"
     */
    host: string;
    /**
     * Allowed path. Supports globs. Empty means "allow all"
     */
    path: string;
    /**
     * ID of the project this token belongs to
     */
    projectId: number;
    /**
     * Slug of the project this token belongs to
     */
    projectSlug: string;
    /**
     * Custom headers which will be added after successfull authorization
     */
    headers?: Array<NameValue>;
    /**
     * Tentative number of requests used this token
     */
    requests: number;
};

export type ListProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects';
};

export type ListProjectsResponses = {
    /**
     * OK
     */
    200: Array<Project>;
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type CreateProjectData = {
    /**
     * Project parameters
     */
    body: ProjectConfig;
    path?: never;
    query?: never;
    url: '/projects';
};

export type CreateProjectResponses = {
    /**
     * OK
     */
    200: Project;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        project: number;
    };
    query?: never;
    url: '/projects/{project}';
};

export type DeleteProjectResponses = {
    /**
     * OK
     */
    204: void;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        project: number;
    };
    query?: never;
    url: '/projects/{project}';
};

export type GetProjectResponses = {
    /**
     * OK
     */
    200: Project;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type UpdateProjectData = {
    /**
     * Project parameters
     */
    body: ProjectPatch;
    path: {
        /**
         * Project ID
         */
        project: number;
    };
    query?: never;
    url: '/projects/{project}';
};

export type UpdateProjectResponses = {
    /**
     * OK
     */
    204: void;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type ListTokensData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter tokens by project ID
         */
        project?: number;
    };
    url: '/tokens';
};

export type ListTokensResponses = {
    /**
     * OK
     */
    200: Array<Token>;
};

export type ListTokensResponse = ListTokensResponses[keyof ListTokensResponses];

export type CreateTokenData = {
    /**
     * Token parameters
     */
    body: TokenConfig;
    path?: never;
    query?: never;
    url: '/tokens';
};

export type CreateTokenResponses = {
    /**
     * OK
     */
    200: Credential;
};

export type CreateTokenResponse = CreateTokenResponses[keyof CreateTokenResponses];

export type DeleteTokenData = {
    body?: never;
    path: {
        /**
         * Token ID
         */
        token: number;
    };
    query?: never;
    url: '/tokens/{token}';
};

export type DeleteTokenResponses = {
    /**
     * OK
     */
    204: void;
};

export type DeleteTokenResponse = DeleteTokenResponses[keyof DeleteTokenResponses];

export type GetTokenData = {
    body?: never;
    path: {
        /**
         * Token ID
         */
        token: number;
    };
    query?: never;
    url: '/tokens/{token}';
};

export type GetTokenResponses = {
    /**
     * OK
     */
    200: Token;
};

export type GetTokenResponse = GetTokenResponses[keyof GetTokenResponses];

export type UpdateTokenData = {
    /**
     * Token parameters
     */
    body: TokenPatch;
    path: {
        /**
         * Token ID
         */
        token: number;
    };
    query?: never;
    url: '/tokens/{token}';
};

export type UpdateTokenResponses = {
    /**
     * OK
     */
    204: void;
};

export type UpdateTokenResponse = UpdateTokenResponses[keyof UpdateTokenResponses];

export type RefreshTokenData = {
    body?: never;
    path: {
        /**
         * Token ID
         */
        token: number;
    };
    query?: never;
    url: '/tokens/{token}';
};

export type RefreshTokenResponses = {
    /**
     * OK
     */
    200: Credential;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];
