// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateProjectOperation OperationName = "CreateProject"
	CreateTokenOperation   OperationName = "CreateToken"
	DeleteProjectOperation OperationName = "DeleteProject"
	DeleteTokenOperation   OperationName = "DeleteToken"
	GetProjectOperation    OperationName = "GetProject"
	GetTokenOperation      OperationName = "GetToken"
	ListProjectsOperation  OperationName = "ListProjects"
	ListTokensOperation    OperationName = "ListTokens"
	RefreshTokenOperation  OperationName = "RefreshToken"
	UpdateProjectOperation OperationName = "UpdateProject"
	UpdateTokenOperation   OperationName = "UpdateToken"
)
