// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"
)

// Ref: #/components/schemas/Credential
type Credential struct {
	// Token ID.
	ID int `json:"id"`
	// Raw token key.
	Key string `json:"key"`
}

// GetID returns the value of ID.
func (s *Credential) GetID() int {
	return s.ID
}

// GetKey returns the value of Key.
func (s *Credential) GetKey() string {
	return s.Key
}

// SetID sets the value of ID.
func (s *Credential) SetID(val int) {
	s.ID = val
}

// SetKey sets the value of Key.
func (s *Credential) SetKey(val string) {
	s.Key = val
}

// DeleteProjectNoContent is response for DeleteProject operation.
type DeleteProjectNoContent struct{}

// DeleteTokenNoContent is response for DeleteToken operation.
type DeleteTokenNoContent struct{}

// Ref: #/components/schemas/NameValue
type NameValue struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// GetName returns the value of Name.
func (s *NameValue) GetName() string {
	return s.Name
}

// GetValue returns the value of Value.
func (s *NameValue) GetValue() string {
	return s.Value
}

// SetName sets the value of Name.
func (s *NameValue) SetName(val string) {
	s.Name = val
}

// SetValue sets the value of Value.
func (s *NameValue) SetValue(val string) {
	s.Value = val
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Project
type Project struct {
	// Unique project ID.
	ID int `json:"id"`
	// Time when project was created.
	CreatedAt time.Time `json:"createdAt"`
	// Time when project was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
	// Unique project slug (path and query friendly).
	Slug string `json:"slug"`
	// Project description.
	Description string `json:"description"`
}

// GetID returns the value of ID.
func (s *Project) GetID() int {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Project) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Project) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetSlug returns the value of Slug.
func (s *Project) GetSlug() string {
	return s.Slug
}

// GetDescription returns the value of Description.
func (s *Project) GetDescription() string {
	return s.Description
}

// SetID sets the value of ID.
func (s *Project) SetID(val int) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Project) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Project) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetSlug sets the value of Slug.
func (s *Project) SetSlug(val string) {
	s.Slug = val
}

// SetDescription sets the value of Description.
func (s *Project) SetDescription(val string) {
	s.Description = val
}

// Ref: #/components/schemas/ProjectConfig
type ProjectConfig struct {
	// Unique project slug (path and query friendly).
	Slug string `json:"slug"`
	// Project description.
	Description OptString `json:"description"`
}

// GetSlug returns the value of Slug.
func (s *ProjectConfig) GetSlug() string {
	return s.Slug
}

// GetDescription returns the value of Description.
func (s *ProjectConfig) GetDescription() OptString {
	return s.Description
}

// SetSlug sets the value of Slug.
func (s *ProjectConfig) SetSlug(val string) {
	s.Slug = val
}

// SetDescription sets the value of Description.
func (s *ProjectConfig) SetDescription(val OptString) {
	s.Description = val
}

// Ref: #/components/schemas/ProjectPatch
type ProjectPatch struct {
	// Project description.
	Description OptString `json:"description"`
}

// GetDescription returns the value of Description.
func (s *ProjectPatch) GetDescription() OptString {
	return s.Description
}

// SetDescription sets the value of Description.
func (s *ProjectPatch) SetDescription(val OptString) {
	s.Description = val
}

// Ref: #/components/schemas/Token
type Token struct {
	// Unique token ID.
	ID int `json:"id"`
	// Time when token was initially created.
	CreatedAt time.Time `json:"createdAt"`
	// Time when token was updated last time.
	UpdatedAt time.Time `json:"updatedAt"`
	// Tentative time when token was last time used.
	LastAccessAt OptDateTime `json:"lastAccessAt"`
	// Unique first several bytes for token which is used for fast identification.
	KeyID string `json:"keyID"`
	// User which created token.
	User string `json:"user"`
	// Custom token description.
	Label string `json:"label"`
	// Allowed hosts. Supports globs. Empty list means "allow all".
	Hosts []string `json:"hosts"`
	// Allowed paths. Supports globs. Empty list means "allow all".
	Paths []string `json:"paths"`
	// ID of the project this token belongs to.
	ProjectId int `json:"projectId"`
	// Slug of the project this token belongs to.
	ProjectSlug string `json:"projectSlug"`
	// Custom headers which will be added after successfull authorization.
	Headers []NameValue `json:"headers"`
	// Tentative number of requests used this token.
	Requests int64 `json:"requests"`
}

// GetID returns the value of ID.
func (s *Token) GetID() int {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Token) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Token) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetLastAccessAt returns the value of LastAccessAt.
func (s *Token) GetLastAccessAt() OptDateTime {
	return s.LastAccessAt
}

// GetKeyID returns the value of KeyID.
func (s *Token) GetKeyID() string {
	return s.KeyID
}

// GetUser returns the value of User.
func (s *Token) GetUser() string {
	return s.User
}

// GetLabel returns the value of Label.
func (s *Token) GetLabel() string {
	return s.Label
}

// GetHosts returns the value of Hosts.
func (s *Token) GetHosts() []string {
	return s.Hosts
}

// GetPaths returns the value of Paths.
func (s *Token) GetPaths() []string {
	return s.Paths
}

// GetProjectId returns the value of ProjectId.
func (s *Token) GetProjectId() int {
	return s.ProjectId
}

// GetProjectSlug returns the value of ProjectSlug.
func (s *Token) GetProjectSlug() string {
	return s.ProjectSlug
}

// GetHeaders returns the value of Headers.
func (s *Token) GetHeaders() []NameValue {
	return s.Headers
}

// GetRequests returns the value of Requests.
func (s *Token) GetRequests() int64 {
	return s.Requests
}

// SetID sets the value of ID.
func (s *Token) SetID(val int) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Token) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Token) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetLastAccessAt sets the value of LastAccessAt.
func (s *Token) SetLastAccessAt(val OptDateTime) {
	s.LastAccessAt = val
}

// SetKeyID sets the value of KeyID.
func (s *Token) SetKeyID(val string) {
	s.KeyID = val
}

// SetUser sets the value of User.
func (s *Token) SetUser(val string) {
	s.User = val
}

// SetLabel sets the value of Label.
func (s *Token) SetLabel(val string) {
	s.Label = val
}

// SetHosts sets the value of Hosts.
func (s *Token) SetHosts(val []string) {
	s.Hosts = val
}

// SetPaths sets the value of Paths.
func (s *Token) SetPaths(val []string) {
	s.Paths = val
}

// SetProjectId sets the value of ProjectId.
func (s *Token) SetProjectId(val int) {
	s.ProjectId = val
}

// SetProjectSlug sets the value of ProjectSlug.
func (s *Token) SetProjectSlug(val string) {
	s.ProjectSlug = val
}

// SetHeaders sets the value of Headers.
func (s *Token) SetHeaders(val []NameValue) {
	s.Headers = val
}

// SetRequests sets the value of Requests.
func (s *Token) SetRequests(val int64) {
	s.Requests = val
}

// Ref: #/components/schemas/TokenConfig
type TokenConfig struct {
	// Custom token description.
	Label OptString `json:"label"`
	// Allowed hosts. Supports globs. Empty list means "allow all".
	Hosts []string `json:"hosts"`
	// Allowed paths. Supports globs. Empty list means "allow all".
	Paths []string `json:"paths"`
	// Custom headers which will be added after successfull authorization.
	Headers []NameValue `json:"headers"`
	// Project ID this token belongs to.
	ProjectId int `json:"projectId"`
}

// GetLabel returns the value of Label.
func (s *TokenConfig) GetLabel() OptString {
	return s.Label
}

// GetHosts returns the value of Hosts.
func (s *TokenConfig) GetHosts() []string {
	return s.Hosts
}

// GetPaths returns the value of Paths.
func (s *TokenConfig) GetPaths() []string {
	return s.Paths
}

// GetHeaders returns the value of Headers.
func (s *TokenConfig) GetHeaders() []NameValue {
	return s.Headers
}

// GetProjectId returns the value of ProjectId.
func (s *TokenConfig) GetProjectId() int {
	return s.ProjectId
}

// SetLabel sets the value of Label.
func (s *TokenConfig) SetLabel(val OptString) {
	s.Label = val
}

// SetHosts sets the value of Hosts.
func (s *TokenConfig) SetHosts(val []string) {
	s.Hosts = val
}

// SetPaths sets the value of Paths.
func (s *TokenConfig) SetPaths(val []string) {
	s.Paths = val
}

// SetHeaders sets the value of Headers.
func (s *TokenConfig) SetHeaders(val []NameValue) {
	s.Headers = val
}

// SetProjectId sets the value of ProjectId.
func (s *TokenConfig) SetProjectId(val int) {
	s.ProjectId = val
}

// Ref: #/components/schemas/TokenPatch
type TokenPatch struct {
	// Custom token description.
	Label OptString `json:"label"`
	// Allowed hosts. Supports globs. Empty list means "allow all".
	Hosts []string `json:"hosts"`
	// Allowed paths. Supports globs. Empty list means "allow all".
	Paths []string `json:"paths"`
	// Custom headers which will be added after successfull authorization.
	Headers []NameValue `json:"headers"`
}

// GetLabel returns the value of Label.
func (s *TokenPatch) GetLabel() OptString {
	return s.Label
}

// GetHosts returns the value of Hosts.
func (s *TokenPatch) GetHosts() []string {
	return s.Hosts
}

// GetPaths returns the value of Paths.
func (s *TokenPatch) GetPaths() []string {
	return s.Paths
}

// GetHeaders returns the value of Headers.
func (s *TokenPatch) GetHeaders() []NameValue {
	return s.Headers
}

// SetLabel sets the value of Label.
func (s *TokenPatch) SetLabel(val OptString) {
	s.Label = val
}

// SetHosts sets the value of Hosts.
func (s *TokenPatch) SetHosts(val []string) {
	s.Hosts = val
}

// SetPaths sets the value of Paths.
func (s *TokenPatch) SetPaths(val []string) {
	s.Paths = val
}

// SetHeaders sets the value of Headers.
func (s *TokenPatch) SetHeaders(val []NameValue) {
	s.Headers = val
}

// UpdateProjectNoContent is response for UpdateProject operation.
type UpdateProjectNoContent struct{}

// UpdateTokenNoContent is response for UpdateToken operation.
type UpdateTokenNoContent struct{}
